name: Periodic checks

on:
  push:
    branches:
      - main
  #schedule:
    #- cron: '15 5 * * *'

jobs:
  health_check:
    runs-on: ubuntu-20.04
    steps:
      - name: Check the deployed service URL
        uses: jtalk/url-health-check-action@v2
        with:
          url: https://cicd-blogapp.herokuapp.com/api/health
          follow-redirect: false
          max-attempts: 3
          retry-delay: 5s
