name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Backend / npm install
        run: npm install
      - name: Frontend / npm install
        working-directory: ./frontend
        run: npm install
      - name: Backend / lint
        run: npm run eslint
      - name: Frontend / lint
        working-directory: ./frontend
        run: npm run eslint
      - name: Build
        working-directory: ./frontend
        run: npm run build
      - name: Backend / test
        run: npm run test
        env:
          TEST_MONGODB_URI: ${{secrets.TEST_MONGODB_URI}}
          PORT: ${{secrets.PORT}}
          SECRET: ${{secrets.SECRET}}
      - name: Frontend / test
        working-directory: ./frontend
        run: npm run test
      - name: E2e tests
        uses: cypress-io/github-action@v2
        env:
          TEST_MONGODB_URI: ${{secrets.TEST_MONGODB_URI}}
          PORT: ${{secrets.PORT}}
          SECRET: ${{secrets.SECRET}}
        with:
          command: npm run test:e2e
          start: npm run start:test
          wait-on: http://localhost:${{secrets.PORT}}
      - name: Heroku deploy
        uses: akhileshns/heroku-deploy@79ef2ae4ff9b897010907016b268fd0f88561820
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "cicd-blogapp"
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          healthcheck: "https://cicd-blogapp.herokuapp.com/api/health"
          checkstring: "ok"
          rollbackonhealthcheckfailed: true
        if: ${{ github.event_name == 'push' && contains(join(github.event.commits.*.message, ', '), '#skip') == false }}

  tag_release:
    needs: [simple_deployment_pipeline]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - name: Bumb version and push tag
        uses: anothrNick/github-tag-action@ce4b5ffa38e072fa7a901e417253c438fcc2ccce
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: "patch"
        if: ${{ github.event_name == 'push' && contains(join(github.event.commits.*.message, ', '), '#skip') == false }}